### ISSUE TITLE
GCC Support / Relative Pathname Macro

### ISSUE THREAD

**Issue by Snoorklo** [Snoorklo/ExC#3]
# GCC Support
`__FILE_NAME__` seems to be clang-only.
Finding an alternative would be really good.

# Relative Path Names
Currently (as far as I know), it only prints the filename. Ideally it'd show the folders up to that file, from the project root.

## Ideal Solution Guidelines
- Must be compile-time, no extra runtime performance hit.
- Must not build in absolute paths into the binary.
- Should run on both Clang and GCC.
- MSVC support would be nice but I don't really care.

**Comment by powpingdone** [comment]
```c
#ifndef __FILE_NAME__
#define __FILE_NAME__ __BASE_NAME__
#endif
```
``__BASE_NAME__`` basically is the line specified on the compiler line.

**Comment by Snoorklo** [comment]
Gonna play around and see if i can do something with CMake and a custom macro, that should be an intermediate solution if nothing works tho.
